name: Development build

env:
  projectVersion: '0.0.2'

on:
  push:
    branches:
      - dev

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      projectName: ${{ steps.project_details.outputs.project_name }}

    steps:
      - uses: actions/checkout@v4
      - name: Extract project details
        id: project_details
        run: |
          echo "PROJECT_NAME=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build Module
        run: |
          mvn -T 1C -B package -Drevision=${{ env.projectVersion }} --file pom.xml

      - name: Upload artifact
        env:
          projectName: ${{ needs.setup.outputs.projectName }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.projectName }}-${{ env.projectVersion }}-b${{ github.run_number }}
          path: target/${{ env.projectName }}-${{ env.projectVersion }}.jar
